@startuml Project Java Fullstack - F-Booking

skinparam ParticipantPadding 50
skinparam BoxPadding 10
left to right direction

skinparam actor {
  backgroundColor #FEFEC8
  borderColor #BD0042
  borderThickness 2
}
skinparam usecase {
  backgroundColor #FEFEC8
  borderColor #BD0042
}
skinparam package {
  backgroundColor #EEEBDC
}

skinparam ArrowColor BD0042
skinparam ArrowThickness 1.5
skinparam UsecaseBorderThickness 2
skinparam PersonBorderThickness 2
' skinparam ArrowFontSize 10
' skinparam ActorFontSize 10
' skinparam UsecaseFontSize 10
package AdminApp{
  usecase "Đăng nhập" as UC_LoginAdmin
  usecase "Danh sách phòng học đăng ký (xem, sửa, xoá)" as UC_RoomAdmin
  usecase "Danh sách bộ phận đăng ký (thêm, sửa, xoá)" as UC_DepartmentsAdmin
}
actor "Quản trị viên" as Admin
'actor "Hệ thống" as System
Admin ---> UC_LoginAdmin
Admin ---> UC_RoomAdmin
Admin ---> UC_DepartmentsAdmin

rectangle Controller{
 ' usecase "/student/\n(GET,POST)" as Rest_Admin
 'usecase "/admin/room/{id}\n(GET,PATCH,DELETE)" as Rest_Admin
  usecase "/admin/room\n(GET,POST,DELETE)" as Rest_RoomAdmin
  usecase "/admin/room/{id}\n(GET,POST,DELETE)" as Rest_Admin
  usecase "/admin/booking_time\n(GET,POST,DELETE)" as Rest_BookingTimeAdmin
  usecase "/admin/booking_time/{id}\n(GET,POST,DELETE)" as Rest_BookingTimeAdmin
  usecase "/departments\n(GET,POST,PATCH,DELETE)" as Rest_DepartmentAdmin
  usecase "/login\n(POST)" as Rest_LoginAdmin
  usecase "/departments/{id}\n(GET)" as Rest_DepartmentAdmin
}
UC_LoginAdmin -> Rest_LoginAdmin
UC_RoomAdmin ---> Rest_RoomAdmin
UC_DepartmentsAdmin ---> Rest_DepartmentAdmin

database MSSQL
Controller <---> MSSQL : transaction via Model


package UserApp {
  usecase "Đăng nhập" as UC_LoginStudent
  usecase "Tra cứu phòng trống" as UC_RoomStudent
  usecase "Booking phòng" as UC_BookingStudent
  usecase "Xác nhận booking phòng" as UC_CheckBookingStudent
}
actor "Người dùng" as Student
'actor "Admin" as Admin
UC_LoginStudent <--- Student
UC_RoomStudent <--- Student
UC_BookingStudent <--- Student
UC_CheckBookingStudent <--- Student


Rest_LoginAdmin <--- UC_LoginStudent
Rest_Admin <--- UC_BookingStudent
Rest_BookingTimeAdmin <--- UC_CheckBookingStudent
Rest_BookingTimeAdmin <--- UC_RoomStudent

@enduml